In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier

import dataset


In [ ]:
credit_df = pd.read_excel('a_Dataset_CreditScoring.xlsx')

In [ ]:
credit_df.head()

TARGET    ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1   582         3           3             0         4          0.0   
1       1   662        15           9             0         3          1.0   
2       1   805         0           0             0         1          5.0   
3       1  1175         8           5             0         6          1.0   
4       1  1373         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  TLBalHCPct  \
0                5          117          27  ...          3.0      0.9179   
1                3           14          14  ...          1.0      0.8000   
2                1          354           7  ...          5.0      0.3552   
3               10           16           4  ...          3.0      0.9127   
4                8          130          52  ...          1.0      1.2511   

   TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  TLOpenPct  \
0    0.2083               2             3              7     0.2083   
1    0.0000               0             0              0     1.0000   
2    0.6538               0             1              1     0.7308   
3    0.2500               1             1              1     0.7500   
4    0.0000               0             1              4     0.1429   

   TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0              4             4       0.0000  
1             12             0       1.0000  
2              1             1       0.5263  
3              7             1       1.3333  
4              3             1       0.0000  

[5 rows x 30 columns]

Data Preparation

In [ ]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   TARGET           3000 non-null   int64  
 1   ID               3000 non-null   int64  
 2   DerogCnt         3000 non-null   int64  
 3   CollectCnt       3000 non-null   int64  
 4   BanruptcyInd     3000 non-null   int64  
 5   InqCnt06         3000 non-null   int64  
 6   InqTimeLast      2812 non-null   float64
 7   InqFinanceCnt24  3000 non-null   int64  
 8   TLTimeFirst      3000 non-null   int64  
 9   TLTimeLast       3000 non-null   int64  
 10  TLCnt03          3000 non-null   int64  
 11  TLCnt12          3000 non-null   int64  
 12  TLCnt24          3000 non-null   int64  
 13  TLCnt            2997 non-null   float64
 14  TLSum            2960 non-null   float64
 15  TLMaxSum         2960 non-null   float64
 16  TLSatCnt         2996 non-null   float64
 17  TLDel60Cnt    

In [ ]:
credit_df.isnull().sum()

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [ ]:
credit_df.drop(['ID'], axis=1, inplace=True)

In [ ]:
credit_df.head(5)

TARGET  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1         3           3             0         4          0.0   
1       1        15           9             0         3          1.0   
2       1         0           0             0         1          5.0   
3       1         8           5             0         6          1.0   
4       1         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  ...  TL50UtilCnt  \
0                5          117          27        0  ...          3.0   
1                3           14          14        0  ...          1.0   
2                1          354           7        0  ...          5.0   
3               10           16           4        0  ...          3.0   
4                8          130          52        0  ...          1.0   

   TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  \
0      0.9179    0.2083               2             3              7   
1      0.8000    0.0000               0             0              0   
2      0.3552    0.6538               0             1              1   
3      0.9127    0.2500               1             1              1   
4      1.2511    0.0000               0             1              4   

   TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0     0.2083              4             4       0.0000  
1     1.0000             12             0       1.0000  
2     0.7308              1             1       0.5263  
3     0.7500              7             1       1.3333  
4     0.1429              3             1       0.0000  

[5 rows x 29 columns]

In [ ]:
credit_df.fillna(credit_df.mean(), inplace=True)

In [ ]:
credit_df['TARGET'].value_counts()

TARGET
0    2500
1     500
Name: count, dtype: int64

In [ ]:
credit_df.groupby('TARGET').mean()

DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
TARGET                                                              
0         1.3224      0.7664        0.1492    2.9424     3.174638   
1         1.9680      1.3100        0.1740    3.9380     2.775459   

        InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  TLCnt12  ...  \
TARGET                                                              ...   
0                3.2896      173.002      11.650   0.2844    1.832  ...   
1                4.8820      155.672      12.992   0.2280    1.768  ...   

        TL50UtilCnt  TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  \
TARGET                                                                    
0          3.986711    0.628177  0.544963          0.6044        0.6624   
1          4.533870    0.748185  0.385173          1.3340        1.5760   

        TLDel60CntAll  TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
TARGET                                                                      
0              2.2236   0.502376          1.180        0.8648     0.556867  
1              4.0140   0.465127          2.554        2.0860     0.600978  

[2 rows x 28 columns]

Train test split

In [ ]:
y = credit_df.iloc[:,0].values
x = credit_df.iloc[:, 1:28].values

In [ ]:
#splitting the dataset into training and testing(80/20)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

Logistic Regression




In [59]:
classifier  = LogisticRegression(solver="newton-cg")
classifier.fit(X_train,y_train)
y_pred_lr = classifier.predict(X_test)

In [60]:
print("Logistic Regression:")
print(confusion_matrix(y_test, y_pred_lr))
print(f"Accuracy: {accuracy_score(y_test, y_pred_lr):.2f}")
print(classification_report(y_test, y_pred_lr))


Logistic Regression:
[[482  16]
 [ 87  15]]
Accuracy: 0.83
              precision    recall  f1-score   support

           0       0.85      0.97      0.90       498
           1       0.48      0.15      0.23       102

    accuracy                           0.83       600
   macro avg       0.67      0.56      0.56       600
weighted avg       0.79      0.83      0.79       600



Using random forest

In [62]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

In [64]:
print("Random Forest Classifier:")
print(confusion_matrix(y_test, y_pred_rf))
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.2f}")

Random Forest Classifier:
[[490   8]
 [ 95   7]]
Accuracy: 0.83


In [65]:
predictions = rf_model.predict(X_test)

# Display Classification Report for Random Forest
print("\nClassification Report:")
print(classification_report(y_test, predictions))


Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.98      0.90       498
           1       0.47      0.07      0.12       102

    accuracy                           0.83       600
   macro avg       0.65      0.53      0.51       600
weighted avg       0.77      0.83      0.77       600



In [72]:
predictions =classifier.predict_proba(X_test)
prob_class_1 = predictions[:, 1]
print(predictions)
print(prob_class_1)

[[0.04218037 0.95781963]
 [0.93692306 0.06307694]
 [0.70468695 0.29531305]
 ...
 [0.97238196 0.02761804]
 [0.44319934 0.55680066]
 [0.86810275 0.13189725]]
[0.95781963 0.06307694 0.29531305 0.09200327 0.13368568 0.10709331
 0.41737795 0.22969145 0.33321503 0.08233361 0.02805732 0.04815554
 0.47472317 0.44356088 0.17373687 0.33330313 0.08263995 0.05926743
 0.06431941 0.1686161  0.16549517 0.35839569 0.02229611 0.10280107
 0.05283402 0.43517186 0.10715489 0.18819992 0.05437263 0.49180804
 0.34753119 0.10431996 0.11637596 0.12308432 0.13100271 0.05720582
 0.43267942 0.25934935 0.08030698 0.34843649 0.02365447 0.20725554
 0.05556086 0.67688755 0.0585346  0.0864427  0.16000966 0.12189533
 0.13814104 0.44258633 0.05235996 0.02753281 0.18991711 0.01485465
 0.32432412 0.04868094 0.08813243 0.15790763 0.03802083 0.08255489
 0.22329133 0.87033921 0.16370611 0.06945902 0.13534927 0.06609559
 0.01710866 0.26116706 0.03947901 0.76527946 0.02851589 0.11635569
 0.07026347 0.05447641 0.0841276  0.0591

In [71]:
predictions_b = classifier.predict(X_test)
predictions_b

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,